# Generated by Django 4.2.6 on 2024-11-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_genders_user_info_joining_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('building', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('domain', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='urgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('color', models.CharField(default='red', max_length=100, null=True)),
                ('urgency', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_domain_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sub_domain', models.CharField(default='', max_length=100, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.domains')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('floor', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('others', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.buildings')),
                ('department', models.ManyToManyField(blank=True, to='Backend.departments')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.cities'),
        ),
    ]
