# Generated by Django 4.2.6 on 2024-11-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_remove_admin_access_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_requests',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.services'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='desk_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.locations'),
        ),
    ]
