# Generated by Django 4.2.6 on 2024-11-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_all_requests_create_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='request_status',
        ),
    ]
