# Generated by Django 4.2.6 on 2024-11-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_rename_status_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_requests',
            name='requestor_department',
            field=models.ManyToManyField(blank=True, to='Backend.departments'),
        ),
        migrations.AddField(
            model_name='all_requests',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.request_status'),
        ),
    ]
