# Generated by Django 4.2.6 on 2024-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_all_request_status_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_request_status_flow',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_requests',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
