# Generated by Django 4.2.6 on 2024-11-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_alter_domain_minimum_access_level_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_requests',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_requests',
            name='rating',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_view_status',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.all_requests'),
        ),
    ]
