# Generated by Django 4.2.6 on 2024-11-18 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('department', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('designation', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('priority', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('color', models.CharField(default='red', max_length=30, null=True)),
                ('status', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('profile_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ManyToManyField(to='Backend.departments')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.designation')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.user_roles')),
            ],
        ),
        migrations.CreateModel(
            name='employee_supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sup', to='Backend.user_info')),
                ('supervisors', models.ManyToManyField(blank=True, to='Backend.user_info')),
            ],
        ),
    ]
