# Generated by Django 4.2.6 on 2024-11-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_buildings_cities_domains_urgency_sub_domains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.TextField(blank=True)),
                ('acknowledge', models.ManyToManyField(blank=True, related_name='acknowledged_requests', to='Backend.user_info')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.domains')),
                ('manager', models.ManyToManyField(blank=True, related_name='managing_requests', to='Backend.user_info')),
                ('request_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_by_user', to='Backend.user_info')),
                ('sub_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.sub_domains')),
                ('urgency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.urgency')),
            ],
        ),
    ]
