# Generated by Django 4.2.6 on 2024-11-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_access_level_access_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='access_priority',
            new_name='admin_access_priority',
        ),
    ]
