# Generated by Django 4.2.6 on 2024-11-20 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_all_requests_desk_number_all_requests_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_requests',
            name='create_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
