# Generated by Django 4.2.6 on 2024-11-20 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_all_requests_requestor_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_request_status_flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.TextField(blank=True)),
                ('update_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='Backend.user_info')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to='Backend.all_requests')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_by_user', to='Backend.request_status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='Backend.user_info')),
            ],
        ),
    ]
