# Generated by Django 4.2.6 on 2024-11-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_alter_all_request_status_flow_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_minimum_access_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmaid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.access_level')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.domains', unique=True)),
            ],
        ),
    ]
