# Generated by Django 4.2.6 on 2024-11-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_all_requests_comment_all_requests_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_requests',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='all_requests',
            name='rating',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
